'use client'
import '../../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarSeller from './NavbarSeller'
import Footer from '../../(Customer)/Footer'
import FooterSeller from './FooterSeller'
import localFont from 'next/font/local'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import SecondLayout from './SecondLayout'


const inter = Inter({ subsets: ['latin'] })
const pimaryFont = localFont({
  src: '../../assets/fonts/Estedad-Regular.ttf',
  // display: 'swap',
})

const queryClient = new QueryClient();

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl' data-theme="light">
      <body className={pimaryFont.className}>
        <QueryClientProvider client={queryClient}>
          <SecondLayout children={children} />
        </QueryClientProvider>
      </body>
    </html>
  )
}
