import '../../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarSeller from './NavbarSeller'
import Footer from '../../(Customer)/Footer'
import FooterSeller from './FooterSeller'
import localFont from 'next/font/local'


const inter = Inter({ subsets: ['latin'] })
const pimaryFont = localFont({
  src: '../../assets/fonts/Estedad-Regular.ttf',
  // display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={pimaryFont.className}>
         <NavbarSeller/>
         <main className='p-5' style={{paddingTop:'85px'}}>
          {children}
         </main>
         <FooterSeller/>
      </body>
      
    </html>
  )
}
