import '../../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarSeller from './NavbarSeller'
import Footer from '../../(Customer)/Footer'
import FooterSeller from './FooterSeller'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir='rtl'>
      <body className={inter.className}>
         <NavbarSeller/>
         <main className='p-5'>
          {children}
         </main>
         <FooterSeller/>
      </body>
      
    </html>
  )
}
