apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: karans-go-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productapi # Name of your deployment
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 10 # Maximum number of replicas
  metrics:
  - type: Resource
    resource:
      name: cpu # You can also use "memory"
      target:
        type: Utilization
        averageUtilization: 30 # Target CPU utilization percentage
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 3
          periodSeconds: 5
    scaleDown:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 3
          periodSeconds: 5
