apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  HOST: mongo-service
  PORT: "27017"
  mongodb.conf: |  
    storage:
      dbPath: /data/db  
    replication:
      replSetName: "rs0"

