apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
      
      - name: userapi
        image: users
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: PORT      
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_PASSWORD   
        - name: JWTSECRET
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: JWTSECRET 
        - name: innerSecret
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: innerSecret         
        ports:
        - containerPort: 3005
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"  
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
spec:
  type: ClusterIP
  selector:
    app: userapi
  ports:
  - port: 3005
    targetPort: 3005
      
